# 服务端口
server:
    port: 8273
spring:
    application:
        name: service-oss
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    # 环境设置：dev、test、prod
    profiles:
        active: prod
    #swagger3整合
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

qiniu:
    accessKey: accessKey
    secretKey: secretKey
    bucketName: bucketName
    url: url

